# Generated by Django 4.1 on 2022-09-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=1000)),
                ("lasttname", models.CharField(max_length=1000)),
                ("email", models.CharField(max_length=1000)),
                ("password", models.CharField(max_length=1000)),
            ],
        ),
    ]
