# Generated by Django 4.1 on 2022-09-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LMSapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admin", old_name="lasttname", new_name="lastname",
        ),
    ]
