# Generated by Django 4.1 on 2022-09-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LMSapp", "0002_rename_lasttname_admin_lastname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admin", old_name="firstname", new_name="username",
        ),
        migrations.RemoveField(model_name="admin", name="lastname",),
    ]
