# Generated by Django 4.1 on 2022-09-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("LMSapp", "0004_delete_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("author", models.CharField(blank=True, max_length=1000)),
                (
                    "no_of_books_available",
                    models.CharField(blank=True, max_length=1000),
                ),
            ],
        ),
    ]
