# Generated by Django 4.1 on 2022-09-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMSapp", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.CharField(max_length=10000, primary_key=True, serialize=False),
        ),
    ]
